### ISSUE TITLE
Broken dependencies

### ISSUE THREAD

**Issue by parrish** [brian-c/haw#7]
Looks like a dependency of the specified version of browserify (I think?) has been unpublished.

Anything preventing an upgrade?  I currently can't deploy sites with haw as a dependency.

**Comment by brian-c** [comment]
Just published 5.0.1 with a bump to browserify. API shouldn't've changed but let me know if anything's weird. How'd you trace it back to browserify? Good find.

**Comment by parrish** [comment]
Thanks! :+1: 
I just went through node_modules trying to install sub-dependencies until one failed

**Comment by parrish** [comment]
Looks good!
